#ifndef MONEYTOR_COMMON_H
#define MONEYTOR_COMMON_H

#include <stdbool.h>

#ifndef NDEBUG
    #define DEBUG_PRINT(...) {printf(__VA_ARGS__); printf("\n");}
#else
    #define DEBUG_PRINT(...) {}
#endif

#define FREE(p)                 \
        do {                    \
            if (p != NULL) {    \
                free(p);        \
            }                   \
            p = NULL;           \
        }                       \
        while(0);               \

typedef enum {
    RETURNCODE_SUCCESS = 0,
    RETURNCODE_LIST_GETLENGTH_LIST_IS_NULL,
    RETURNCODE_LIST_REMOVEELEMENT_LIST_IS_NULL,
    RETURNCODE_LIST_REMOVEELEMENT_LIST_EMPTY,
    RETURNCODE_LIST_REMOVEELEMENT_ELEMENT_NOT_FOUND,
    RETURNCODE_LIST_REMOVEELEMENT_FAILED_TO_FREE_DATA_MEMORY,
    RETURNCODE_LIST_ADDELEMENT_LIST_NULL,
    RETURNCODE_LIST_ADDELEMENT_MEMORY_ALLOCATION_FAILED,
    RETURNCODE_LIST_DESTROY_FAILED_TO_FREE_DATA_MEMORY,
    RETURNCODE_LIST_PRINT_LIST_IS_NULL,
    RETURNCODE_LIST_PRINT_NOT_ALL_ELEMENTS_PRINTED,
    RETURNCODE_LIST_GETNEXT_LIST_NULL,
    RETURNCODE_LIST_GETNEXT_LAST_ELEMENT,
    RETURNCODE_LIST_GETNEXT_CURRENT_ELEMENT_NOT_FOUND,
    RETURNCODE_LIST_COPY_PARAMETER_NULL,
    RETURNCODE_LIST_COPY_FAILED_CREATE_NEW_LIST,
    RETURNCODE_LIST_COPY_FAILED_TO_ADD_ELEMENT,
    RETURNCODE_LIST_COPY_FAILED_TO_COPY_ELEMENT,
    RETURNCODE_MAIN_INVALID_ARGUMENT_NUMBER,
    RETURNCODE_MAIN_MEMORY_ALOOCATION_FAILED,
    RETURNCODE_MAIN_COULDNT_OPEN_GIVEN_FOLDER,
    RETURNCODE_MAIN_UNINITIALIZED
} returnCode_t;

#endif //MONEYTOR_COMMON_H
