#ifndef MONEYTOR_MONEYTORDEFINITIONS_H
#define MONEYTOR_MONEYTORDEFINITIONS_H

#define DEBUG_PRINT(...) {printf(__VA_ARGS__); printf("\n");}
#define TRUE 1
#define FALSE 0


#endif //MONEYTOR_MONEYTORDEFINITIONS_H
